---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnivore-postgres
  labels:
    app: omnivore
    component: postgres
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: omnivore-postgres
  labels:
    app: omnivore
    component: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: omnivore
    component: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnivore-postgres
  labels:
    app: omnivore
    component: postgres
spec:
  selector:
    matchLabels:
      app: omnivore
      component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omnivore
        component: postgres
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: init-chmod-data
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 999:999 /var/lib/postgresql/data &&
              chmod 700 /var/lib/postgresql/data
          securityContext:
            runAsUser: 0 # run as root to change permissions
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      containers:
        - name: postgres
          image: ankane/pgvector:v0.5.1
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: omnivore-postgres-admin
            - secretRef:
                name: omnivore-postgres
          livenessProbe:
            exec:
              command: ["exit", "0"]
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 12
            failureThreshold: 3
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/postgresql/data"
              subPath: postgres
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: omnivore-postgres
