apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnivore-redis
  labels:
    app: omnivore
    component: redis
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: omnivore-redis
  labels:
    app: omnivore
    component: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: omnivore
    component: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnivore-redis
  labels:
    app: omnivore
    component: redis
spec:
  selector:
    matchLabels:
      app: omnivore
      component: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omnivore
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2.4
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: storage
              mountPath: "/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: omnivore-redis
